//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagement_VNR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string Door_Number { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public int Pincode { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
